services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./db/data:/data
  web:
    image: ghcr.io/n2o/url-shortener:latest
    ports:
      - "8080:8080"
    env_file:
      - production.env