version: "3.7"
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./db/data:/data
  web:
    image: cmeter/url-shortener
    ports:
      - "8080:8080"
    env_file:
      - production.env