name: Heroku

on:
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run Gradle Checks
        run: ./gradlew check

      - name: Deploy to Heroku
        uses: actions/heroku@1.0.0