name: Heroku Deployment

on:
  push:
    branches:
      - auto_deploy_heroku # this is only for the first test run, will be master in production

jobs:
  deploy:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "theshorty"
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master