name: Heroku Deployment

on:
  push:
    branches:
      - auto_deploy_heroku # this is only for the first test run, will be master in production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - name: Create remote
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku git:remote --app=theshorty
      - name: Push and Build
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

        run: git push heroku HEAD:refs/heads/master